### ISSUE TITLE
RSS Memory Leak

### ISSUE THREAD

**Issue by dt-atkinson** [medooze/media-server-node#101] opened 2019-08-21 15:17 UTC
I believe to have found another memory leak. I will try to get a test project to reproduce. This is a more difficult one for me to find however because it is RSS memory and *not* the nodejs heap.

This leads me to assume it is in the C++ native library - would that be the correct assumption?

Bad graph below (Purple is RSS others are heap used/total):
[Screenshot 2019-08-21 at 16 02 09](https://user-images.githubusercontent.com/35025856/63443745-46171100-c42d-11e9-96c4-11654d8e8032.png)

This is a node which is constantly having WebRTC endpoints and transports created/torn down. 

I have another benchmark which just keeps connection online broadcasting which does not leak so its presumably an issue with things not being cleaned up on destruction.

**Comment by murillo128** [comment] 2019-08-21 23:54
seems so. Is it linear to the number of created/destroyed  endpoints/transports?

**Comment by dt-atkinson** [comment] 2019-08-22 10:59
Yeah I don't think its affecting the actual use of the service it's just filling up my log files! :)

I can get a network capture going to reproduce it but it might have to be next week. Few things to do!

**Comment by dt-atkinson** [comment] 2019-09-18 15:06
Try this:
https://github.com/dt-atkinson/medooze-memory-leak

**Comment by murillo128** [comment] 2019-09-18 15:50
could it be related to this?
https://github.com/medooze/media-server-node/issues/69

it shouldn't be much memory per run, but didn't knew you were doing so intensive tests.

**Comment by dt-atkinson** [comment] 2019-09-18 16:07
Not sure - how do I disable this?

I am just trying to recreate memory leaks that happen on my production instances. They heavy reuse endpoints and transports so the memory grows over the days.

**Comment by murillo128** [comment] 2019-09-18 16:08
I will try to fix #69 and see if this also is closed

**Comment by dt-atkinson** [comment] 2019-09-18 16:08
Okay great, I'll be here to re-run the tests and try to trace down any other areas I can find issues!

**Comment by murillo128** [comment] 2019-09-19 22:53
It was indeed a duplicate of #69 

After  the fix and including a `gc()` on each interval:
![image](https://user-images.githubusercontent.com/1070835/65283781-37a93b80-db38-11e9-91cd-6944bf0f4e24.png)

**Closed** 2019-09-19 22:54 UTC
Labels: duplicate

**Comment by dt-atkinson** [comment] 2019-09-23 11:02
Retesting this and under stress testing and this looks to be well resolved. Great!
